#!/usr/bin/env python3
"""Distill archived review rounds into per-topic skill playbooks.

The self-improvement loop already knows what went wrong (the archive) and
which class each finding belongs to (the policy). This turns that into the
artifact an eve-style agent loads on demand: one Markdown skill per topic,
saying what the class of problem looks like, how often it recurred, and how
it was fixed where a round recorded that. The next fix starts from what the
loop already learned, so the loop improves the doer, not only the judge.

Only text that is already public enters a skill: review findings archived
from pull-request comments, and proposal/fix notes written by hand. Working
session excerpts never do.

usage: distill-skills.py [ARCHIVE] [--policy PATH] [--out-dir DIR]
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT_DIR = REPO_ROOT / "agents" / "self-improver" / "skills"
MAX_EXAMPLES = 8


def _load_sibling_module(name: str, filename: str):
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, Path(__file__).parent / filename)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


policy_mod = _load_sibling_module("improvement_policy", "improvement_policy.py")


def load_archive(path: str | Path) -> list[dict]:
    return [json.loads(line) for line in Path(path).read_text().splitlines() if line.strip()]


def distill(entries: list[dict], policy: dict) -> dict[str, dict]:
    """Per topic: rounds it recurred in, example findings (public review
    text, scrubbed), and the recorded fixes."""
    keywords = policy_mod.topic_keywords(policy)
    skills: dict[str, dict] = {
        topic: {"keywords": list(words), "rounds": [], "examples": [], "fixes": []}
        for topic, words in keywords.items()
    }
    seen_rounds: dict[str, set[str]] = defaultdict(set)
    for entry in entries:
        key = policy_mod.round_key(entry)
        round_num = entry.get("round")
        for finding in entry.get("findings", []) or []:
            if not isinstance(finding, str):
                continue
            topic = policy_mod.classify_finding(finding, keywords)
            if topic is None:
                continue
            skill = skills[topic]
            if key not in seen_rounds[topic]:
                seen_rounds[topic].add(key)
                skill["rounds"].append(round_num)
            example = {
                "round": round_num,
                "finding": policy_mod.scrub_secrets(finding).strip()[:300],
            }
            if len(skill["examples"]) < MAX_EXAMPLES and example not in skill["examples"]:
                skill["examples"].append(example)
            note = entry.get("mechanism_change_note") or entry.get("fixes_applied")
            if note and isinstance(note, str) and entry.get("kept"):
                fix = {"round": round_num, "how": policy_mod.scrub_secrets(note).strip()[:400]}
                if fix not in skill["fixes"]:
                    skill["fixes"].append(fix)
    return skills


def render(topic: str, skill: dict, threshold: int) -> str:
    rounds = skill["rounds"]
    lines = [
        f"# Skill: {topic}",
        "",
        f"Load this before changing anything that touches: {', '.join(f'`{k}`' for k in skill['keywords'])}.",
        "",
        "## How this class of problem shows up",
        "",
    ]
    if skill["examples"]:
        lines += [f"- Round {e['round']}: {e['finding']}" for e in skill["examples"]]
    else:
        lines.append("- No archived review finding has been filed under this topic yet.")
    lines += [
        "",
        "## Recurrence",
        "",
        f"Recurred in {len(rounds)} round(s)"
        + (f": {', '.join(str(r) for r in rounds)}" if rounds else "")
        + f". Mechanism-fix threshold: {threshold}.",
        "",
        "## How it was fixed",
        "",
    ]
    if skill["fixes"]:
        lines += [f"- Round {f['round']}: {f['how']}" for f in skill["fixes"]]
    else:
        lines.append(
            "- No round recorded a mechanism-level fix note for this topic yet. When you fix "
            "one, say how in the round's `mechanism_change_note` and this section fills in."
        )
    lines += [
        "",
        "## Before you push",
        "",
        "- Search your diff and its tests for the keywords above; each hit is a place a reviewer has flagged before.",
        "- If the fix is a mechanism (a guard, a check, a workflow rule), add the regression test that fails without it.",
        "",
        "_Generated by `scripts/distill-skills.py` from `docs/self-improvement-archive.jsonl`; do not edit by hand._",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "archive_path",
        nargs="?",
        default=str(REPO_ROOT / "docs" / "self-improvement-archive.jsonl"),
    )
    parser.add_argument("--policy", default=None)
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR))
    args = parser.parse_args(argv[1:])

    policy = (
        policy_mod.load_policy(args.policy) if args.policy else policy_mod.load_policy_or_builtin()
    )
    entries = load_archive(args.archive_path)
    skills = distill(entries, policy)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    for topic, skill in skills.items():
        target = out_dir / f"{topic}.md"
        policy_mod.assert_safe_output(target, inputs=[args.archive_path, args.policy])
        target.write_text(render(topic, skill, policy["threshold"]))
        written.append(policy_mod.relative_to_repo(target))
    # Skills for topics the policy no longer has are stale: remove them.
    for stale in out_dir.glob("*.md"):
        if stale.name != "README.md" and stale.stem not in skills:
            stale.unlink()
    print(json.dumps({"policy_version": policy["version"], "skills": written}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
